# Funding configuration for this repository.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# Uncomment and fill in the platforms you use. Multiple platforms are supported.

# github: [mlaify]
# ko_fi: # Replace with a single Ko-fi username
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
# liberapay: # Replace with a single Liberapay username
# patreon: # Replace with a single Patreon username
# custom: # Replace with up to 4 custom sponsorship URLs
