[[main]]
  name = "Aegis"
  url = "/aegis/"
  weight = 10

[[main]]
  name = "AttackMap"
  url = "/attackmap/"
  weight = 20

[[main]]
  name = "Open Source"
  url = "/docs/projects/"
  weight = 30

[[main]]
  name = "About"
  url = "/about/"
  weight = 40

[[footer]]
  name = "About"
  url = "/about/"
  weight = 10

[[footer]]
  name = "Build Principles"
  url = "/build-principles/"
  weight = 20

[[footer]]
  name = "Contribute"
  url = "/contribute/"
  weight = 30

[[footer]]
  name = "Privacy"
  url = "/privacy/"
  weight = 40

[[footer]]
  name = "Security"
  url = "/security/"
  weight = 50

[[footer]]
  name = "GitHub"
  url = "https://github.com/mlaify"
  weight = 60

[[social]]
  name = "GitHub"
  url = "https://github.com/mlaify"
  weight = 10
