[[main]]
  name = "Writing"
  url = "/writing/"
  weight = 10

[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[main]]
  name = "About"
  url = "/about/"
  weight = 30

[[footer]]
  name = "About"
  url = "/about/"
  weight = 10

[[footer]]
  name = "Projects"
  url = "/projects/"
  weight = 15

[[footer]]
  name = "Archives"
  url = "/writing/"
  weight = 20

[[footer]]
  name = "Principles"
  url = "/principles/"
  weight = 25

[[footer]]
  name = "Contribute"
  url = "/contribute/"
  weight = 28

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 30

[[footer]]
  name = "Security"
  url = "/security/"
  weight = 40

[[footer]]
  name = "GitHub"
  url = "https://github.com/mlaify"
  weight = 50

[[social]]
  name = "Bluesky"
  url = "https://bsky.app/profile/mlaify.io"
  weight = 10

[[social]]
  name = "GitHub"
  url = "https://github.com/mlaify"
  weight = 20

[[social]]
  name = "GitLab"
  url = "https://gitlab.com/mlaify"
  weight = 30
